apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
  namespace: grade-submission
data:
  init-replicaset.sh: |
    #!/bin/bash
    echo "Waiting for MongoDB to be ready..."

    # Wait for MongoDB to be ready
    until mongo --eval "db.adminCommand('ping')" > /dev/null 2>&1; do
      echo "MongoDB is not ready yet, retrying..."
      sleep 2
    done

    echo "MongoDB is ready!"

    # Check if replica set is already initialized
    RS_STATUS=$(mongo --quiet --eval "rs.status().ok" 2>/dev/null || echo "0")

    if [ "$RS_STATUS" != "1" ]; then
      echo "Initializing replica set..."
      mongo --eval '
      rs.initiate({
        _id: "rs0",
        members: [
          { _id: 0, host: "mongodb-0.mongodb-headless.grade-submission.svc.cluster.local:27017" },
          { _id: 1, host: "mongodb-1.mongodb-headless.grade-submission.svc.cluster.local:27017" }
        ]
      })'
      echo "Replica set initialized!"
    else
      echo "Replica set already initialized."
    fi
