version: '3'
services:
  flask-app:
    image: rslim087/grade-submission-portal
    container_name: flask-app
    ports:
      - "5001:5001"
    environment:
      - GRADE_SERVICE_HOST=node-server
    depends_on:
      - node-server

  node-server:
    image: rslim087/grade-submission-api:2.0.0
    container_name: node-server
    environment: 
      - DB_HOST=mongo-db
      - DB_PORT=27017
      - DB_NAME=grade_db
    ports:
      - "3000:3000"

  mongo-db:
    image: mongo
    container_name: mongo-db
    environment: 
      - MONGO_INITDB_DATABASE=grade_db
    volumes:
      - mongo-db-data:/data/db

volumes:
  mongo-db-data: